### PR TITLE
Update sensitivity text

### PR DESCRIPTION
**Pull request by kellijohnson**
The branch was rebased with @andrew-edwards ' latest before I committed. Note in my commit message that the following should be looked at because I didn't know if you had already fixed it or if I would mess something up by fixing it.
The sens.models.5 are currently wrong in the figure rnw because some
don't match up with the right model b/c I think that sens.models.5 was
split into two different sens.models, i.e., 5 and 6.
Also, need to remove catch.levels argument from make.decision.table.
I couldn't push a branch to @cgrandin so I thought I would do this route of a pull request. We can also forgo this and I can adopt the convention of merging. Just let me know.

### CODE REVIEW

**Comment by andrew-edwards** [comment]
Rebase confuses me in general! And I think it gets messy if it's not a simple thing.

I think we have to stick with 
- fork off Chris on GitHub
- clone to your computer
- commit and push to your own fork
- look at Network Graph and merge in whoever is furthest ahead of you (this is good because if say, Aaron is working on some text that I'm not bothered with right now, I know I won't have conflicts so can not bother merging for a while)

**Comment by cgrandin** [comment]
To so it this way, you need to add all of us as remotes:

`git remote -v` to see what you remotes are
`git remote add aberger https://github.com/aaronmberger/hake-assessment`
etc for each of us.

When I look at my remotes using `git remote -v`, they look like this:
```
aberger https://github.com/aaronmberger/hake-assessment (fetch)
aberger https://github.com/aaronmberger/hake-assessment (push)
aedwards        https://github.com/andrew-edwards/hake-assessment (fetch)
aedwards        https://github.com/andrew-edwards/hake-assessment (push)
itaylor https://github.com/taylori/hake-assessment (fetch)
itaylor https://github.com/taylori/hake-assessment (push)
kjohnson        https://github.com/kellijohnson/hake-assessment (fetch)
kjohnson        https://github.com/kellijohnson/hake-assessment (push)
origin  https://github.com/cgrandin/hake-assessment (fetch)
origin  https://github.com/cgrandin/hake-assessment (push)
```

If your origin shows my URL, change it to yours using the same method as above

**Comment by cgrandin** [comment]
Then when you look at the network graph, you can merge us individually:

`git fetch cgrandin`
`git diff cgrandin/master`  (if you want to see what you're about to merge in
`git merge cgrandin/master` (or rebase if you want - we tend to use merge to keep the network graph branched out)

**Comment by andrew-edwards** [comment]
And the Network Graph takes a while to refresh sometimes. You usually look at your own to see if you need to fetch anyone else's. 

I just merged you guys and can see I'm up-to-date:

https://github.com/andrew-edwards/hake-assessment/network

(though Ian shows up as way back, but he only did a merge). Of course, the graph may change by the time you look at it!

**Pull request merged**
